###
GET Http://localhost:8089/index

###
GET Http://localhost:8089/name

###
GET Http://localhost:8089/students

###
GET Http://localhost:8089/os/students

###
GET Http://localhost:8089/students/1

###
POST Http://localhost:8089/students
Content-Type: application/json

{"id":"3","name":"Steve","age":"52","subject":"MobilPhone"}

###
POST Http://localhost:8089/os/students
Content-Type: application/json

{"id":"3","name":"Steve","age":"52","subject":"MobilPhone"}

###
PUT Http://localhost:8089/students/3 HTTP/1.1 
Content-Type: application/json

{"id":"3","name":"Steve","age":"52","subject":"MobilPhone"}

###
DELETE Http://localhost:8089/students/2 HTTP/1.1

###
GET Http://localhost:8089/download HTTP/1.1

###
GET Http://localhost:8089/indexPage HTTP/1.1